"""empty message

Revision ID: 1fd902e19c81
Revises: 6500c350f3ca
Create Date: 2023-01-14 16:50:49.818608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd902e19c81'
down_revision = '6500c350f3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites_planets', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorites_planets_planet_id_key', type_='unique')
        batch_op.drop_constraint('user_favorites_planets_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_favorites_planets_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('user_favorites_planets_planet_id_key', ['planet_id'])

    # ### end Alembic commands ###
