"""empty message

Revision ID: 6500c350f3ca
Revises: 58685e13c7f0
Create Date: 2023-01-14 16:38:08.312022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6500c350f3ca'
down_revision = '58685e13c7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites_people')
    with op.batch_alter_table('user_favorites_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_favorites_planets_planets_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['planet_id'])
        batch_op.drop_constraint('user_favorites_planets_planets_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])
        batch_op.drop_column('planets_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_favorites_planets_planets_id_fkey', 'planet', ['planets_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_favorites_planets_planets_id_key', ['planets_id'])
        batch_op.drop_column('planet_id')

    op.create_table('user_favorites_people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='user_favorites_people_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_favorites_people_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_favorites_people_pkey'),
    sa.UniqueConstraint('people_id', name='user_favorites_people_people_id_key'),
    sa.UniqueConstraint('user_id', name='user_favorites_people_user_id_key')
    )
    # ### end Alembic commands ###
